"""One-shot generator for backend/data/space/catalog.json — run from backend root."""

from __future__ import annotations

import json
from pathlib import Path

NEXT = {
    "space-in-plain-sight",
    "space-as-infrastructure",
    "thai-space-story",
    "orbit-sense",
    "low-earth",
    "who-sees-whom",
    "harsh-space",
    "heat-and-shadow",
    "the-point-of-flying",
    "the-ground-station",
    "catch-the-pass",
    "ground-and-ops",
    "earth-from-orbit",
    "space-for-thailand",
}


def folder(id_: str, title: str, title_th: str, summary: str, children: list) -> dict:
    return {
        "kind": "folder",
        "id": id_,
        "title": title,
        "titleTh": title_th,
        "summary": summary,
        "children": children,
    }


def course(
    id_: str,
    title: str,
    title_th: str,
    summary: str,
    *,
    teaches: list[str],
    audience: str,
    intent_hints: list[str],
    recommend_when: list[str],
    tags: list[str] | None = None,
    level: str = "intro",
    prerequisites: list[str] | None = None,
    related: list[str] | None = None,
    do_not_confuse: list[str] | None = None,
    arena_hooks: list[str] | None = None,
    outline: list[dict] | None = None,
    status: str | None = None,
) -> dict:
    if status is None:
        if id_ == "cubesat-for-beginner":
            status = "published"
        elif id_ in NEXT:
            status = "coming_soon"
        else:
            status = "later"
    return {
        "kind": "course",
        "id": id_,
        "title": title,
        "titleTh": title_th,
        "summary": summary,
        "status": status,
        "level": level,
        "tags": tags or [],
        "teaches": teaches,
        "audience": audience,
        "intentHints": intent_hints,
        "prerequisites": prerequisites or [],
        "relatedCourseIds": related or [],
        "recommendWhen": recommend_when,
        "doNotConfuseWith": do_not_confuse or [],
        "arenaHooks": arena_hooks or [],
        "outline": outline,
    }


def main() -> None:
    catalog = {
        "domainId": "space-technology",
        "title": "Space Technology",
        "titleTh": "เทคโนโลยีอวกาศ",
        "summary": (
            "โดเมนการเรียนรู้เทคโนโลยีอวกาศของ Lunar — "
            "ไม่จำกัดแค่ดาวเทียม CubeSat เป็นหัวข้อนำร่อง"
        ),
        "nodes": [
            folder(
                "around-us",
                "AROUND US",
                "อวกาศรอบตัว",
                "ทำไมอวกาศเกี่ยวกับเรา วงโคจร และสภาพที่ของบนฟ้าต้องทน",
                [
                    folder(
                        "why-space",
                        "WHY SPACE",
                        "ทำไมต้องมี",
                        "บทบาทอวกาศในชีวิตประจำวัน เศรษฐกิจ และบริบทไทย",
                        [
                            course(
                                "space-in-plain-sight",
                                "SPACE IN PLAIN SIGHT",
                                "อวกาศที่อยู่รอบตัว",
                                "ของบนฟ้าอยู่ในชีวิตประจำวันโดยไม่ต้องเห็นจรวด",
                                teaches=["everyday space services", "why learn space tech"],
                                audience="คนที่ยังไม่แน่ใจว่าอวกาศเกี่ยวกับตัวเองยังไง",
                                intent_hints=[
                                    "อวกาศเกี่ยวกับชีวิตประจำวันยังไง",
                                    "ทำไมต้องเรียนเทคโนโลยีอวกาศ",
                                ],
                                recommend_when=["unknown-intent", "why-space", "beginner-orientation"],
                                tags=["foundations", "everyday"],
                                do_not_confuse=["cubesat-for-beginner"],
                                related=["thai-space-story", "orbit-sense"],
                            ),
                            course(
                                "space-as-infrastructure",
                                "SPACE AS INFRASTRUCTURE",
                                "อวกาศคือโครงสร้างพื้นฐาน",
                                "สื่อสาร นำทาง ภาพ เวลา เป็นสาธารณูปโภค",
                                teaches=["comm nav imaging as infrastructure", "hidden space services"],
                                audience="คนที่อยากเห็นอวกาศเป็นระบบพื้นฐานของโลก",
                                intent_hints=["อวกาศเป็นโครงสร้างพื้นฐาน", "GPS มาจากไหน"],
                                recommend_when=["why-space", "infrastructure"],
                                tags=["foundations", "infrastructure"],
                                related=["find-your-signal", "link-from-space", "earth-from-orbit"],
                            ),
                            course(
                                "who-pays-for-space",
                                "WHO PAYS FOR SPACE",
                                "ใครจ่าย ใครใช้",
                                "เศรษฐกิจอวกาศแบบจับต้องได้ ไม่ใช่แค่นาซา",
                                teaches=["space economy actors", "who pays who uses"],
                                audience="คนที่สนใจธุรกิจและคุณค่าทางเศรษฐกิจ",
                                intent_hints=["เศรษฐกิจอวกาศ", "ใครทำเงินจากดาวเทียม"],
                                recommend_when=["career", "economy"],
                                tags=["economy"],
                            ),
                            course(
                                "thai-space-story",
                                "THAI SPACE STORY",
                                "อวกาศไทยมีอะไรมาแล้ว",
                                "ผลงานและหน่วยงานในประเทศ ทำไม CubeSat ถึงโชว์ได้",
                                teaches=["Thai space context", "why CubeSat is a local entry"],
                                audience="คนที่อยากเห็นบริบทไทยก่อนลงมือ",
                                intent_hints=["อวกาศไทย", "ไทยมีดาวเทียมไหม"],
                                recommend_when=["thailand", "why-space", "beginner-orientation"],
                                tags=["thailand", "foundations"],
                                related=["space-for-thailand", "cubesat-for-beginner"],
                            ),
                        ],
                    ),
                    folder(
                        "orbits",
                        "ORBITS",
                        "วงโคจร",
                        "วงโคจรแบบเห็นภาพ ครอบคลุม และหน้าต่างผ่าน",
                        [
                            course(
                                "orbit-sense",
                                "ORBIT SENSE",
                                "วงโคจรแบบเห็นภาพ",
                                "ตกค้างฟ้า ความสูงต่างกันงานต่างกัน",
                                teaches=["what an orbit is", "LEO MEO GEO intuition"],
                                audience="ทุกคนที่เริ่มเรียน Space",
                                intent_hints=["วงโคจรคืออะไร", "LEO ต่างจาก GEO ยังไง"],
                                recommend_when=["orbits", "beginner-orientation"],
                                tags=["orbits"],
                                related=["low-earth", "high-and-parked"],
                            ),
                            course(
                                "low-earth",
                                "LOW EARTH",
                                "ชีวิตใน LEO",
                                "วงใกล้ ผ่านเร็ว eclipse หน้าต่างสั้น บ้านของ CubeSat",
                                teaches=["LEO lifestyle", "eclipse fraction", "short passes"],
                                audience="คนที่สนใจของบินใกล้โลก",
                                intent_hints=["LEO คืออะไร", "ทำไม CubeSat อยู่ LEO"],
                                recommend_when=["orbits", "build-satellite"],
                                tags=["orbits", "leo"],
                                level="beginner",
                                prerequisites=["orbit-sense"],
                                related=["harsh-space", "cubesat-for-beginner"],
                            ),
                            course(
                                "high-and-parked",
                                "HIGH AND PARKED",
                                "MEO / GEO",
                                "นำทางกับสื่อสารทำไมอยู่สูงกว่า",
                                teaches=["MEO for GNSS", "GEO parked longitude"],
                                audience="คนที่สนใจนำทางและสื่อสาร",
                                intent_hints=["GEO คืออะไร", "ทำไมทีวีจากดาวเทียม"],
                                recommend_when=["orbits", "gnss", "comms"],
                                tags=["orbits", "geo"],
                            ),
                            course(
                                "who-sees-whom",
                                "WHO SEES WHOM",
                                "เส้นทางบนโลกกับหน้าต่างผ่าน",
                                "กราวด์แทร็ก ครอบคลุม ทำไมไทยเห็น LEO เป็นช่วง ๆ",
                                teaches=["ground track", "coverage", "pass windows"],
                                audience="คนที่สนใจว่าสถานีเห็นดาวเทียมเมื่อไหร่",
                                intent_hints=["หน้าต่างผ่าน", "ทำไมคุยกับดาวเทียมไม่ได้ทั้งวัน"],
                                recommend_when=["orbits", "ground-ops"],
                                tags=["orbits", "ground"],
                                related=["catch-the-pass", "the-ground-station"],
                            ),
                            course(
                                "many-in-formation",
                                "MANY IN FORMATION",
                                "บินเป็นกลุ่ม",
                                "หลายดวงทำงานร่วมกันแบบ intuition",
                                teaches=["constellation intuition", "formation idea"],
                                audience="คนที่สงสัยว่าทำไมต้องหลายดวง",
                                intent_hints=["กลุ่มดาวเทียม", "ทำไม GPS ต้องหลายดวง"],
                                recommend_when=["orbits", "constellation"],
                                tags=["orbits"],
                                related=["constellations", "find-your-signal"],
                            ),
                        ],
                    ),
                    folder(
                        "environment",
                        "ENVIRONMENT",
                        "สภาพอวกาศ",
                        "สุญญากาศ อุณหภูมิ รังสี ขยะอวกาศ",
                        [
                            course(
                                "harsh-space",
                                "HARSH SPACE",
                                "อยู่รอดในอวกาศ",
                                "สุญญากาศ ร้อนเย็น รังสี รวมภาพแรก",
                                teaches=["vacuum", "thermal extremes", "radiation overview"],
                                audience="คนที่อยากรู้ว่าทำไมของบนฟ้าพังง่าย",
                                intent_hints=["อวกาศอันตรายยังไง", "ทำไมต้องทนสุญญากาศ"],
                                recommend_when=["environment", "physics"],
                                tags=["environment"],
                                related=["heat-and-shadow", "radiation-hit"],
                            ),
                            course(
                                "heat-and-shadow",
                                "HEAT AND SHADOW",
                                "ร้อน เย็น เงาโลก",
                                "แดดเต็ม / เงาโลก / ฮีตเตอร์",
                                teaches=["eclipse thermal", "heater role"],
                                audience="คนที่เรียนพลังงานและอุณหภูมิ",
                                intent_hints=["eclipse หนาวไหม", "ทำไมต้องมีฮีตเตอร์"],
                                recommend_when=["environment", "build-satellite"],
                                tags=["environment", "thermal"],
                                level="beginner",
                                related=["power-on-orbit", "cubesat-for-beginner"],
                            ),
                            course(
                                "radiation-hit",
                                "RADIATION HIT",
                                "รังสีกับอิเล็กทรอนิกส์",
                                "Van Allen, upset, ทำไมอิเล็กทรอนิกส์พลิกบิตได้",
                                teaches=["Van Allen", "SEU intuition"],
                                audience="คนที่เรียนฟิสิกส์หรืออิเล็กทรอนิกส์บนฟ้า",
                                intent_hints=["Van Allen", "SEU คืออะไร"],
                                recommend_when=["environment", "physics"],
                                tags=["environment", "radiation"],
                            ),
                            course(
                                "crowded-sky",
                                "CROWDED SKY",
                                "ขยะอวกาศ",
                                "เศษซาก การชน ความหนาแน่นบนทางหลวงฟ้า",
                                teaches=["debris risk", "crowded orbits"],
                                audience="คนที่สนใจความยั่งยืนของวงโคจร",
                                intent_hints=["ขยะอวกาศ", "ดาวเทียมชนกัน"],
                                recommend_when=["environment", "policy"],
                                tags=["environment", "debris"],
                            ),
                        ],
                    ),
                ],
            ),
            folder(
                "access",
                "ACCESS",
                "ขึ้นสู่อวกาศ",
                "ทางขึ้น rideshare จรวด และชั่วโมงแรกบนฟ้า",
                [
                    folder(
                        "rideshare",
                        "RIDESHARE",
                        "นั่งไปกับคนอื่น",
                        "ขึ้นวงโดยไม่ต้องเป็นเจ้าของจรวด",
                        [
                            course(
                                "path-to-orbit",
                                "PATH TO ORBIT",
                                "ทางขึ้นสู่วงโคจร",
                                "จากพื้นถึงวงโคจร โดยไม่ต้องเป็นเจ้าของจรวด",
                                teaches=["rideshare mindset", "path to orbit"],
                                audience="คนที่อยากรู้ว่าของเล็กขึ้นฟ้ายังไง",
                                intent_hints=["ปล่อยดาวเทียมยังไง", "rideshare"],
                                recommend_when=["launch", "access"],
                                tags=["launch"],
                            ),
                            course(
                                "the-deployer",
                                "THE DEPLOYER",
                                "กล่องปล่อยดาวเทียม",
                                "CubeSat ถูกยัดและดีดยังไง",
                                teaches=["deployer role", "ejection"],
                                audience="คนที่สนใจขั้นตอนหลังขึ้นจรวด",
                                intent_hints=["deployer คืออะไร", "CubeSat ถูกปล่อยยังไง"],
                                recommend_when=["launch", "cubesat"],
                                tags=["launch", "cubesat"],
                            ),
                            course(
                                "ticket-to-fly",
                                "TICKET TO FLY",
                                "ข้อจำกัดตอนจองที่บนจรวด",
                                "มวล ปริมาตร ความถี่ ความปลอดภัย",
                                teaches=["mass volume constraints", "launch safety limits"],
                                audience="คนที่ออกแบบของให้ขึ้นไปได้",
                                intent_hints=["ข้อจำกัดตอนปล่อย", "มวลเท่าไหร่ขึ้นได้"],
                                recommend_when=["launch", "constraints"],
                                tags=["launch", "constraints"],
                            ),
                        ],
                    ),
                    folder(
                        "vehicles",
                        "VEHICLES",
                        "ตัวปล่อย",
                        "จรวดและเส้นทางขึ้นฟ้าแบบ conceptual",
                        [
                            course(
                                "rockets",
                                "ROCKETS",
                                "จรวดคืออะไร",
                                "ตัวปล่อยทำงานแบบ conceptual ไม่ลงสูตรเชื้อเพลิง",
                                teaches=["rocket as launcher", "staging intuition"],
                                audience="คนที่อยากเข้าใจจรวดโดยไม่เป็นวิศวะจรวด",
                                intent_hints=["จรวดทำงานยังไง"],
                                recommend_when=["launch"],
                                tags=["launch", "rockets"],
                            ),
                            course(
                                "small-launchers",
                                "SMALL LAUNCHERS",
                                "จรวดเล็ก",
                                "ทางเลือกปล่อยของเล็ก",
                                teaches=["small launcher niche"],
                                audience="คนที่สนใจทางเลือกปล่อยเฉพาะ",
                                intent_hints=["จรวดเล็ก", "small launcher"],
                                recommend_when=["launch"],
                                tags=["launch"],
                            ),
                            course(
                                "the-ride-up",
                                "THE RIDE UP",
                                "เส้นทางขึ้นฟ้าแบบเห็นภาพ",
                                "ขึ้น แยกขั้น เข้าวง",
                                teaches=["ascent story", "injection intuition"],
                                audience="คนที่อยากเห็นลำดับขึ้นฟ้า",
                                intent_hints=["ตอนขึ้นจรวดเกิดอะไร"],
                                recommend_when=["launch"],
                                tags=["launch"],
                            ),
                        ],
                    ),
                    folder(
                        "first-hours",
                        "FIRST HOURS",
                        "ชั่วโมงแรกบนฟ้า",
                        "หลังแยกจากจรวดจนเริ่มภารกิจ",
                        [
                            course(
                                "leaving-the-rocket",
                                "LEAVING THE ROCKET",
                                "ออกจากจรวด",
                                "ดีด หมุน แผงยังไม่กาง",
                                teaches=["deployment tumble", "first moments"],
                                audience="คนที่สนใจช่วงหลังปล่อย",
                                intent_hints=["หลังปล่อยเกิดอะไร", "detumble"],
                                recommend_when=["launch", "ops"],
                                tags=["launch", "ops"],
                            ),
                            course(
                                "first-light",
                                "FIRST LIGHT",
                                "เปิดตาครั้งแรก",
                                "detumble แผง บีคอน commissioning",
                                teaches=["commissioning", "first beacon"],
                                audience="คนที่สนใจเริ่มปฏิบัติการ",
                                intent_hints=["commissioning", "เปิดแผงโซลาร์"],
                                recommend_when=["ops", "build-satellite"],
                                tags=["ops"],
                            ),
                        ],
                    ),
                ],
            ),
            folder(
                "flight",
                "FLIGHT",
                "ของที่บิน",
                "แพลตฟอร์ม ระบบบนยาน และการสั่งงาน — CubeSat เป็นกิ่งนำร่อง",
                [
                    folder(
                        "platforms",
                        "PLATFORMS",
                        "แพลตฟอร์ม",
                        "CubeSat และของบินแบบอื่น",
                        [
                            folder(
                                "cubesat",
                                "CUBESAT",
                                "ดาวเทียมเล็กมาตรฐาน",
                                "มาตรฐาน 10 ซม. และคอร์สนำร่องของ Lunar",
                                [
                                    course(
                                        "cubesat-for-beginner",
                                        "CUBESAT FOR BEGINNER",
                                        "พื้นฐานดาวเทียมเล็ก",
                                        "ภาพรวม กายวิภาค ฟิสิกส์ สั่งงาน — หัวข้อนำร่องที่มีบทเรียนจริง",
                                        teaches=[
                                            "CubeSat overview",
                                            "subsystem map",
                                            "orbit physics for beginners",
                                            "sense-decide-act toward Arena",
                                        ],
                                        audience="คนที่อยากจับต้องของบินเล็กและฝึกใน Arena",
                                        intent_hints=[
                                            "อยากสร้าง CubeSat",
                                            "อยากเรียนประกอบดาวเทียม",
                                            "อยากเขียนโปรแกรมสั่งดาวเทียม",
                                        ],
                                        recommend_when=["build-satellite", "cubesat", "code"],
                                        tags=["cubesat", "pilot", "published"],
                                        level="beginner",
                                        related=["orbit-sense", "the-point-of-flying"],
                                        do_not_confuse=["space-for-thailand", "earth-from-orbit"],
                                        arena_hooks=["leo-orbit-one-lap"],
                                        outline=[
                                            {
                                                "id": "overview",
                                                "title": "Overview of Satellite",
                                                "summary": "วงโคจร ภารกิจ พิพิธภัณฑ์ CubeSat",
                                            },
                                            {
                                                "id": "anatomy",
                                                "title": "Anatomy of CubeSat",
                                                "summary": "ชิ้นส่วน ไฟ/ข้อมูล",
                                            },
                                            {
                                                "id": "physics",
                                                "title": "Physics for Space",
                                                "summary": "eclipse รังสี งบพลังงาน",
                                            },
                                            {
                                                "id": "programming",
                                                "title": "Programming for CubeSat",
                                                "summary": "sense-decide-act → Arena",
                                            },
                                        ],
                                    ),
                                    course(
                                        "why-ten-centimeters",
                                        "WHY TEN CENTIMETERS",
                                        "ทำไมเป็นกล่อง 10 ซม.",
                                        "มาตรฐาน rideshare 1U–12U ทำอะไรได้ไม่ได้",
                                        teaches=["form factor", "1U limits"],
                                        audience="คนที่สงสัยมาตรฐานขนาด",
                                        intent_hints=["1U คืออะไร", "ทำไม 10 ซม."],
                                        recommend_when=["cubesat"],
                                        tags=["cubesat"],
                                    ),
                                    course(
                                        "cubesat-parade",
                                        "CUBESAT PARADE",
                                        "ภารกิจ CubeSat จริง",
                                        "ดูของจริงและภารกิจตัวอย่าง",
                                        teaches=["real CubeSat missions"],
                                        audience="คนที่อยากเห็นตัวอย่างจริง",
                                        intent_hints=["CubeSat จริงมีอะไรบ้าง"],
                                        recommend_when=["cubesat"],
                                        tags=["cubesat"],
                                    ),
                                ],
                            ),
                            folder(
                                "other-craft",
                                "OTHER CRAFT",
                                "ของบินแบบอื่น",
                                "ของที่ไม่ใช่ CubeSat แต่ยังเป็นเทคโนโลยีอวกาศ",
                                [
                                    course(
                                        "small-satellites",
                                        "SMALL SATELLITES",
                                        "ดาวเทียมที่ใหญ่กว่า CubeSat",
                                        "เมื่อ 1U ไม่พอ",
                                        teaches=["beyond 1U platforms"],
                                        audience="คนที่ต้องการความสามารถมากกว่า CubeSat",
                                        intent_hints=["ดาวเทียมเล็กที่ไม่ใช่ CubeSat"],
                                        recommend_when=["platforms"],
                                        tags=["platforms"],
                                    ),
                                    course(
                                        "big-birds",
                                        "BIG BIRDS",
                                        "ดาวเทียมสื่อสาร / ถ่ายภาพใหญ่",
                                        "ของที่คนใช้ทุกวัน แต่ไม่ได้ประกอบเอง",
                                        teaches=["large EO and comm sats"],
                                        audience="คนที่สนใจของใหญ่บนฟ้า",
                                        intent_hints=["ดาวเทียมสื่อสาร", "ดาวเทียมถ่ายภาพใหญ่"],
                                        recommend_when=["platforms", "comms", "earth-app"],
                                        tags=["platforms"],
                                    ),
                                    course(
                                        "high-altitude",
                                        "HIGH ALTITUDE",
                                        "บอลลูนและยานสูง",
                                        "ของที่เกือบอวกาศ ใช้สอนได้โดยไม่ขึ้นวงโคจร",
                                        teaches=["near-space platforms"],
                                        audience="คนที่อยากทดลองใกล้พื้น",
                                        intent_hints=["บอลลูนอวกาศ", "high altitude"],
                                        recommend_when=["platforms"],
                                        tags=["platforms"],
                                    ),
                                    course(
                                        "beyond-earth",
                                        "BEYOND EARTH",
                                        "ออกจากโลก",
                                        "โพรบ ดวงจันทร์ เป็นกิ่งเปิด ไม่ใช่แกนนำร่อง",
                                        teaches=["beyond-Earth probes"],
                                        audience="คนที่สนใจภารกิจนอกโลก",
                                        intent_hints=["ไปดวงจันทร์", "โพรบ"],
                                        recommend_when=["deep-space"],
                                        tags=["platforms"],
                                    ),
                                ],
                            ),
                        ],
                    ),
                    folder(
                        "bus",
                        "BUS",
                        "ระบบเลี้ยงเพย์โหลด",
                        "ไฟ คอม ทิศทาง วิทยุ เพย์โหลด — ใช้ร่วมได้หลายแพลตฟอร์ม",
                        [
                            course(
                                "the-stack",
                                "THE STACK",
                                "ซ้อนบอร์ดแล้วอยู่รอด",
                                "โครง ราง ชั้นบอร์ด โครงสร้าง",
                                teaches=["structure stack", "mechanisms intro"],
                                audience="คนที่อยากรู้กายภาพของบัส",
                                intent_hints=["โครงสร้างดาวเทียม", "stack board"],
                                recommend_when=["hardware", "build-satellite"],
                                tags=["bus", "structure"],
                            ),
                            course(
                                "power-on-orbit",
                                "POWER ON ORBIT",
                                "ไฟบนฟ้า",
                                "โซลาร์ แบต โหลด งบพลังงานหนึ่งวง",
                                teaches=["EPS", "power budget"],
                                audience="คนที่สนใจพลังงาน",
                                intent_hints=["แบตดาวเทียม", "power budget"],
                                recommend_when=["hardware", "eps"],
                                tags=["bus", "eps"],
                                level="beginner",
                            ),
                            course(
                                "keep-it-warm",
                                "KEEP IT WARM",
                                "อุณหภูมิ",
                                "passive / ฮีตเตอร์ / ทำไม eclipse หนาว",
                                teaches=["thermal control"],
                                audience="คนที่เรียนอุณหภูมิบนฟ้า",
                                intent_hints=["ควบคุมอุณหภูมิดาวเทียม"],
                                recommend_when=["hardware", "thermal"],
                                tags=["bus", "thermal"],
                            ),
                            course(
                                "the-brain",
                                "THE BRAIN",
                                "คอมพิวเตอร์บนยาน",
                                "loop หลัก โหมด ไฟล์โปรแกรม",
                                teaches=["OBC", "modes", "flight software shape"],
                                audience="คนที่สนใจซอฟต์แวร์บนยาน",
                                intent_hints=["OBC คืออะไร", "คอมพิวเตอร์บนดาวเทียม"],
                                recommend_when=["hardware", "code"],
                                tags=["bus", "obc"],
                            ),
                            course(
                                "point-this-way",
                                "POINT THIS WAY",
                                "ทิศทางและการทรงตัว",
                                "หันแผง หันเสา หันกล้อง",
                                teaches=["ADCS intuition"],
                                audience="คนที่สงสัยว่าทำไมต้องชี้ทิศ",
                                intent_hints=["ADCS", "ทำไมต้องหันดาวเทียม"],
                                recommend_when=["hardware", "adcs"],
                                tags=["bus", "adcs"],
                            ),
                            course(
                                "talk-bands",
                                "TALK BANDS",
                                "วิทยุบนยาน",
                                "ขึ้นลิงก์ ลงลิงก์ คุยได้แค่ตอนผ่าน",
                                teaches=["spacecraft radio", "uplink downlink"],
                                audience="คนที่สนใจสื่อสารบนยาน",
                                intent_hints=["วิทยุดาวเทียม", "uplink downlink"],
                                recommend_when=["hardware", "comms"],
                                tags=["bus", "comm"],
                            ),
                            course(
                                "the-point-of-flying",
                                "THE POINT OF FLYING",
                                "เพย์โหลด คือเหตุผลที่ขึ้นไป",
                                "กล้อง เซนเซอร์ วิทยุ งานทดลอง",
                                teaches=["payload is the mission", "duty cycle"],
                                audience="คนที่อยากรู้ว่าขึ้นไปเพื่ออะไร",
                                intent_hints=["payload คืออะไร", "ทำไมต้องมีกล้อง"],
                                recommend_when=["payload", "earth-app", "build-satellite"],
                                tags=["bus", "payload"],
                                related=["earth-from-orbit", "cubesat-for-beginner"],
                                do_not_confuse=["space-in-plain-sight"],
                            ),
                        ],
                    ),
                    folder(
                        "software",
                        "SOFTWARE",
                        "สั่งงาน",
                        "ตรรกะบนยาน — ต่อกับ Arena ได้",
                        [
                            course(
                                "sense-decide-act",
                                "SENSE DECIDE ACT",
                                "รับรู้ ตัดสิน ลงมือ",
                                "โมเดลซอฟต์แวร์ของ Lunar",
                                teaches=["sense decide act loop"],
                                audience="คนที่เริ่มเขียนตรรกะภารกิจ",
                                intent_hints=["โปรแกรมดาวเทียมคิดยังไง"],
                                recommend_when=["code", "build-satellite"],
                                tags=["software"],
                                arena_hooks=["leo-orbit-one-lap"],
                            ),
                            course(
                                "live-through-eclipse",
                                "LIVE THROUGH ECLIPSE",
                                "รอดช่วงไม่มีแดด",
                                "ตรรกะหนึ่งวง: แดด เงา แบต งาน",
                                teaches=["eclipse survival logic"],
                                audience="คนที่ฝึก Arena / พลังงาน",
                                intent_hints=["รอด eclipse ยังไง"],
                                recommend_when=["code", "eps"],
                                tags=["software"],
                                arena_hooks=["leo-orbit-one-lap"],
                            ),
                            course(
                                "safe-mode",
                                "SAFE MODE",
                                "โหมดปลอดภัย",
                                "ตัดงาน เหลือตัวเอง",
                                teaches=["safe mode strategy"],
                                audience="คนที่เรียนโหมดบนยาน",
                                intent_hints=["safe mode คืออะไร"],
                                recommend_when=["code", "ops"],
                                tags=["software"],
                            ),
                        ],
                    ),
                ],
            ),
            folder(
                "ground",
                "GROUND",
                "ภาคพื้น",
                "สถานี ปฏิบัติการ และหลายดวง",
                [
                    folder(
                        "station",
                        "STATION",
                        "สถานี",
                        "ฮาร์ดแวร์ภาคพื้นกับหน้าต่างผ่าน",
                        [
                            course(
                                "the-ground-station",
                                "THE GROUND STATION",
                                "สถานีภาคพื้นคืออะไร",
                                "จาน วิทยุ คอมพิวเตอร์ คน",
                                teaches=["ground station parts"],
                                audience="คนที่สนใจคุยกับของบนฟ้าจากพื้น",
                                intent_hints=["สถานีภาคพื้น", "ground station"],
                                recommend_when=["ground-ops"],
                                tags=["ground"],
                                related=["catch-the-pass", "ground-and-ops"],
                            ),
                            course(
                                "catch-the-pass",
                                "CATCH THE PASS",
                                "จับหน้าต่างผ่าน",
                                "ตารางผ่าน เล็ง เริ่ม-จบการคุย",
                                teaches=["pass planning", "contact window"],
                                audience="คนที่อยากรู้ว่าเมื่อไหร่คุยได้",
                                intent_hints=["จับ pass", "หน้าต่างผ่านไทย"],
                                recommend_when=["ground-ops", "orbits"],
                                tags=["ground"],
                                prerequisites=["who-sees-whom"],
                            ),
                        ],
                    ),
                    folder(
                        "ops",
                        "OPS",
                        "ปฏิบัติการ",
                        "วงจรปฏิบัติการทั้งภารกิจ",
                        [
                            course(
                                "ground-and-ops",
                                "GROUND AND OPS",
                                "จากพื้นคุยกับฟ้า",
                                "วงจรปฏิบัติการทั้งภารกิจ",
                                teaches=["ops loop", "plan uplink downlink"],
                                audience="คนที่อยากทำงานปฏิบัติการ",
                                intent_hints=["ปฏิบัติการดาวเทียม", "mission ops"],
                                recommend_when=["ground-ops", "career"],
                                tags=["ground", "ops"],
                            ),
                            course(
                                "housekeeping",
                                "HOUSEKEEPING",
                                "ของบนฟ้าบอกอะไรกลับมา",
                                "แบต อุณหภูมิ โหมด เหตุการณ์",
                                teaches=["telemetry housekeeping"],
                                audience="คนที่อ่านสถานะยาน",
                                intent_hints=["telemetry", "housekeeping"],
                                recommend_when=["ground-ops"],
                                tags=["ground"],
                            ),
                            course(
                                "command-from-home",
                                "COMMAND FROM HOME",
                                "ส่งคำสั่งจากพื้น",
                                "เปลี่ยนค่า ไม่ต้องเขียนโปรแกรมใหม่ทุกครั้ง",
                                teaches=["telecommand", "parameter tables"],
                                audience="คนที่สนใจสั่งงานจากพื้น",
                                intent_hints=["ส่งคำสั่งดาวเทียม", "telecommand"],
                                recommend_when=["ground-ops", "code"],
                                tags=["ground"],
                            ),
                        ],
                    ),
                    folder(
                        "many-birds",
                        "MANY BIRDS",
                        "หลายดวง",
                        "กลุ่มดาวเทียมและการกลับมาถ่ายซ้ำ",
                        [
                            course(
                                "constellations",
                                "CONSTELLATIONS",
                                "กลุ่มดาวเทียม",
                                "ทำไมงานบางอย่างดวงเดียวไม่พอ",
                                teaches=["why many satellites"],
                                audience="คนที่สนใจ coverage",
                                intent_hints=["กลุ่มดาวเทียมทำไม"],
                                recommend_when=["constellation", "earth-app"],
                                tags=["ground"],
                            ),
                            course(
                                "revisit",
                                "REVISIT",
                                "กลับมาถ่ายจุดเดิมเมื่อไหร่",
                                "ความถี่การกลับมา vs ครอบคลุม",
                                teaches=["revisit vs coverage"],
                                audience="คนที่ใช้ภาพซ้ำตามเวลา",
                                intent_hints=["revisit", "ถ่ายจุดเดิมบ่อยแค่ไหน"],
                                recommend_when=["earth-app", "orbits"],
                                tags=["ground", "eo"],
                            ),
                        ],
                    ),
                ],
            ),
            folder(
                "for-earth",
                "FOR EARTH",
                "ใช้บนโลก",
                "เอาข้อมูล/บริการจากอวกาศมาใช้บนพื้นโลก โดยไม่จำเป็นต้องประกอบดาวเทียมก่อน",
                [
                    folder(
                        "seeing",
                        "SEEING",
                        "มองโลก",
                        "ภาพถ่ายจากวงโคจร",
                        [
                            course(
                                "earth-from-orbit",
                                "EARTH FROM ORBIT",
                                "มองโลกจากบนฟ้า",
                                "ภาพจากวงโคจร ความละเอียด แถบกวาด เมฆ",
                                teaches=["EO basics", "resolution swath clouds"],
                                audience="คนที่อยากใช้ภาพจากอวกาศ",
                                intent_hints=["ภาพถ่ายดาวเทียม", "remote sensing เบื้องต้น"],
                                recommend_when=["earth-app"],
                                tags=["eo"],
                                do_not_confuse=["cubesat-for-beginner"],
                                related=["space-for-thailand", "the-point-of-flying"],
                            ),
                            course(
                                "color-beyond-eyes",
                                "COLOR BEYOND EYES",
                                "สีที่ตาไม่เห็น",
                                "ช่วงคลื่น พืชสะท้อนอะไร",
                                teaches=["spectral bands", "NIR intuition"],
                                audience="คนที่อ่านภาพวิเคราะห์",
                                intent_hints=["NIR", "ช่วงคลื่นภาพดาวเทียม"],
                                recommend_when=["earth-app"],
                                tags=["eo"],
                            ),
                            course(
                                "change-over-time",
                                "CHANGE OVER TIME",
                                "โลกเปลี่ยน เราเห็นจากบน",
                                "ภาพซ้ำ จับความเปลี่ยน",
                                teaches=["change detection"],
                                audience="คนที่ติดตามพื้นที่ตามเวลา",
                                intent_hints=["change detection", "ภาพซ้ำ"],
                                recommend_when=["earth-app"],
                                tags=["eo"],
                            ),
                        ],
                    ),
                    folder(
                        "thailand",
                        "THAILAND",
                        "ใช้ในไทย",
                        "เคสในประเทศ — ไม่ต้องผ่าน CubeSat ก่อน",
                        [
                            course(
                                "space-for-thailand",
                                "SPACE FOR THAILAND",
                                "อวกาศเพื่อไทย",
                                "ภาพรวมการใช้ในประเทศ",
                                teaches=["Thai use cases overview"],
                                audience="คนที่อยากเห็นประโยชน์ในไทย",
                                intent_hints=["อวกาศช่วยไทยยังไง", "เกษตรจากดาวเทียม"],
                                recommend_when=["thailand", "earth-app", "unknown-intent"],
                                tags=["thailand", "eo"],
                                do_not_confuse=["cubesat-for-beginner"],
                                related=["earth-from-orbit", "thai-space-story"],
                            ),
                            course(
                                "rice-from-orbit",
                                "RICE FROM ORBIT",
                                "นาและพืช",
                                "เกษตรจากข้อมูลอวกาศ",
                                teaches=["crop monitoring intuition"],
                                audience="คนที่สนใจเกษตร",
                                intent_hints=["ดูนาจากดาวเทียม", "เกษตรอวกาศ"],
                                recommend_when=["thailand", "earth-app", "agriculture"],
                                tags=["thailand", "eo"],
                            ),
                            course(
                                "water-and-flood",
                                "WATER AND FLOOD",
                                "น้ำท่วมและแหล่งน้ำ",
                                "น้ำจากมุมมองวงโคจร",
                                teaches=["flood and water EO"],
                                audience="คนที่สนใจภัยน้ำ",
                                intent_hints=["น้ำท่วมจากดาวเทียม"],
                                recommend_when=["thailand", "earth-app", "disaster"],
                                tags=["thailand", "eo"],
                            ),
                            course(
                                "forest-and-haze",
                                "FOREST AND HAZE",
                                "ป่าและฝุ่น",
                                "ป่า ไฟ ฝุ่น",
                                teaches=["forest haze monitoring"],
                                audience="คนที่สนใจป่าและอากาศ",
                                intent_hints=["ไฟป่าจากดาวเทียม", "ฝุ่น PM"],
                                recommend_when=["thailand", "earth-app"],
                                tags=["thailand", "eo"],
                            ),
                            course(
                                "sea-and-fish",
                                "SEA AND FISH",
                                "ทะเลและประมง",
                                "ชายฝั่ง ประมง",
                                teaches=["coastal fishery EO"],
                                audience="คนที่สนใจทะเล",
                                intent_hints=["ประมงกับดาวเทียม", "ชายฝั่ง"],
                                recommend_when=["thailand", "earth-app"],
                                tags=["thailand", "eo"],
                            ),
                        ],
                    ),
                    folder(
                        "finding",
                        "FINDING",
                        "หาตำแหน่ง",
                        "GNSS และเวลาจากฟ้า",
                        [
                            course(
                                "find-your-signal",
                                "FIND YOUR SIGNAL",
                                "นำทางจากอวกาศ",
                                "GNSS ในมือถือมาจากกลุ่มดาว",
                                teaches=["GNSS constellation idea"],
                                audience="ทุกคนที่ใช้แผนที่ในมือถือ",
                                intent_hints=["GPS ทำงานยังไง", "GNSS"],
                                recommend_when=["gnss", "everyday"],
                                tags=["gnss"],
                            ),
                            course(
                                "time-from-space",
                                "TIME FROM SPACE",
                                "เวลาจากฟ้า",
                                "เวลาแม่นเป็นบริการที่ซ่อนอยู่",
                                teaches=["timing from GNSS"],
                                audience="คนที่สนใจโครงสร้างพื้นฐานเวลา",
                                intent_hints=["เวลามาจากดาวเทียม"],
                                recommend_when=["gnss", "infrastructure"],
                                tags=["gnss"],
                            ),
                        ],
                    ),
                    folder(
                        "talking",
                        "TALKING",
                        "สื่อสาร",
                        "ลิงก์จากอวกาศสู่ผู้ใช้บนพื้น",
                        [
                            course(
                                "link-from-space",
                                "LINK FROM SPACE",
                                "สื่อสารจากอวกาศ",
                                "ภาพรวมลิงก์",
                                teaches=["satcom overview"],
                                audience="คนที่สนใจสื่อสาร",
                                intent_hints=["สื่อสารดาวเทียม"],
                                recommend_when=["comms"],
                                tags=["comms"],
                            ),
                            course(
                                "internet-from-orbit",
                                "INTERNET FROM ORBIT",
                                "อินเทอร์เน็ตจากวงโคจร",
                                "LEO broadband vs CubeSat",
                                teaches=["LEO broadband vs smallsat"],
                                audience="คนที่เปรียบเทียบบริการสื่อสาร",
                                intent_hints=["เน็ตจากดาวเทียม", "Starlink"],
                                recommend_when=["comms"],
                                tags=["comms"],
                                do_not_confuse=["cubesat-for-beginner"],
                            ),
                            course(
                                "iot-from-space",
                                "IOT FROM SPACE",
                                "ส่งข้อมูลเล็กจากของไกล",
                                "เซนเซอร์สนาม ส่งผ่านดาวเทียม",
                                teaches=["IoT from space"],
                                audience="คนที่สนใจเซนเซอร์ระยะไกล",
                                intent_hints=["IoT ดาวเทียม"],
                                recommend_when=["comms", "iot"],
                                tags=["comms"],
                            ),
                        ],
                    ),
                    folder(
                        "science",
                        "SCIENCE",
                        "วิทยาศาสตร์จากฟ้า",
                        "อากาศอวกาศและภูมิอากาศ",
                        [
                            course(
                                "space-weather",
                                "SPACE WEATHER",
                                "อากาศอวกาศ",
                                "พายุสุริยะ ผลต่อของบนฟ้าและบนดิน",
                                teaches=["space weather effects"],
                                audience="คนที่สนใจรังสีและพายุสุริยะ",
                                intent_hints=["space weather", "พายุสุริยะ"],
                                recommend_when=["science", "environment"],
                                tags=["science"],
                            ),
                            course(
                                "climate-from-above",
                                "CLIMATE FROM ABOVE",
                                "ภูมิอากาศจากวงโคจร",
                                "เซนเซอร์ภูมิอากาศ",
                                teaches=["climate sensing from orbit"],
                                audience="คนที่สนใจภูมิอากาศ",
                                intent_hints=["ภูมิอากาศจากดาวเทียม"],
                                recommend_when=["science", "earth-app"],
                                tags=["science", "eo"],
                            ),
                        ],
                    ),
                ],
            ),
            folder(
                "mission",
                "MISSION",
                "ออกแบบภารกิจ",
                "บีบปัญหา ข้อจำกัด และคนในห่วงโซ่",
                [
                    folder(
                        "shape",
                        "SHAPE",
                        "บีบปัญหา",
                        "จากไอเดียเป็นภารกิจ",
                        [
                            course(
                                "pick-a-problem",
                                "PICK A PROBLEM",
                                "เลือกปัญหาบนโลก",
                                "บีบไอเดียให้เล็กพอทำ",
                                teaches=["problem framing"],
                                audience="คนที่เข้า Studio / มีไอเดีย",
                                intent_hints=["เลือกปัญหาภารกิจ", "เริ่มออกแบบภารกิจ"],
                                recommend_when=["mission-design", "studio"],
                                tags=["mission"],
                            ),
                            course(
                                "mission-canvas",
                                "MISSION CANVAS",
                                "วาดภารกิจ",
                                "หนึ่งหน้า: ปัญหา วงโคจร เพย์โหลด ของเลี้ยง ภาคพื้น",
                                teaches=["one-page mission canvas"],
                                audience="คนที่พร้อมร่างภารกิจ",
                                intent_hints=["mission canvas", "ออกแบบภารกิจ"],
                                recommend_when=["mission-design", "studio"],
                                tags=["mission"],
                            ),
                        ],
                    ),
                    folder(
                        "limits",
                        "LIMITS",
                        "ข้อจำกัดที่สอน",
                        "มวล ไฟ ช่องลงข้อมูล และการรอดก่อนทำงาน",
                        [
                            course(
                                "mass-power-downlink",
                                "MASS POWER DOWNLINK",
                                "มวล ไฟ ช่องส่งข้อมูล",
                                "ข้อจำกัดที่บังคับให้เลือก",
                                teaches=["mass power downlink trade"],
                                audience="คนที่ออกแบบภายใต้ข้อจำกัด",
                                intent_hints=["ข้อจำกัดภารกิจ", "trade-off ดาวเทียม"],
                                recommend_when=["mission-design", "constraints"],
                                tags=["mission"],
                            ),
                            course(
                                "alive-first",
                                "ALIVE FIRST",
                                "รอดก่อน แล้วค่อยทำงาน",
                                "ภารกิจสวย ของตาย = ไม่ผ่าน",
                                teaches=["survival before science"],
                                audience="คนที่ฝึก Arena หรือออกแบบบัส",
                                intent_hints=["รอดก่อนทำงาน", "survive then science"],
                                recommend_when=["mission-design", "build-satellite"],
                                tags=["mission"],
                                arena_hooks=["leo-orbit-one-lap"],
                            ),
                        ],
                    ),
                    folder(
                        "people",
                        "PEOPLE",
                        "คน",
                        "อาชีพและบทบาทในห่วงโซ่",
                        [
                            course(
                                "space-careers",
                                "SPACE CAREERS",
                                "เส้นทางอาชีพ",
                                "ระบบ ซอฟต์แวร์ ops ข้อมูล ผลิตภัณฑ์ในไทย",
                                teaches=["career paths in space tech"],
                                audience="คนที่วางเส้นทางอาชีพ",
                                intent_hints=["ทำงานด้านอวกาศ", "อาชีพอวกาศไทย"],
                                recommend_when=["career"],
                                tags=["career"],
                            ),
                            course(
                                "who-flies-this",
                                "WHO FLIES THIS",
                                "ทีมไหนทำอะไร",
                                "บทบาทคนในห่วงโซ่",
                                teaches=["roles in the chain"],
                                audience="คนที่อยากเห็นภาพทีม",
                                intent_hints=["ทีมภารกิจมีใครบ้าง"],
                                recommend_when=["career", "ops"],
                                tags=["career"],
                            ),
                        ],
                    ),
                ],
            ),
            folder(
                "more",
                "MORE",
                "เส้นทางอื่น",
                "ยังไม่นำร่อง แต่ยังเป็น Lunar ได้",
                [
                    folder(
                        "human",
                        "HUMAN",
                        "มนุษย์ในอวกาศ",
                        "คนขึ้นไปและอยู่บนสถานี",
                        [
                            course(
                                "human-spaceflight",
                                "HUMAN SPACEFLIGHT",
                                "มนุษย์อวกาศ",
                                "คนขึ้นไป",
                                teaches=["human spaceflight intro"],
                                audience="คนที่สนใจมนุษย์ในอวกาศ",
                                intent_hints=["มนุษย์อวกาศ"],
                                recommend_when=["human"],
                                tags=["human"],
                            ),
                            course(
                                "living-in-orbit",
                                "LIVING IN ORBIT",
                                "อยู่บนสถานี",
                                "ชีวิตประจำวันบนสถานี",
                                teaches=["life on station"],
                                audience="คนที่อยากรู้ชีวิตบนสถานี",
                                intent_hints=["อยู่บนสถานีอวกาศ"],
                                recommend_when=["human"],
                                tags=["human"],
                            ),
                        ],
                    ),
                    folder(
                        "rules",
                        "RULES",
                        "กติกา",
                        "นโยบาย คลื่น และกติกาท้องฟ้า",
                        [
                            course(
                                "space-policy",
                                "SPACE POLICY",
                                "นโยบายอวกาศ",
                                "ประเทศกับอวกาศ",
                                teaches=["space policy intro"],
                                audience="คนที่สนใจนโยบาย",
                                intent_hints=["นโยบายอวกาศ"],
                                recommend_when=["policy"],
                                tags=["policy"],
                            ),
                            course(
                                "who-owns-the-spectrum",
                                "WHO OWNS THE SPECTRUM",
                                "คลื่นใครใช้ได้",
                                "สิทธิ์คลื่น",
                                teaches=["spectrum rights intuition"],
                                audience="คนที่สนใจคลื่นสื่อสาร",
                                intent_hints=["คลื่นดาวเทียม", "spectrum"],
                                recommend_when=["policy", "comms"],
                                tags=["policy"],
                            ),
                            course(
                                "rules-of-the-sky",
                                "RULES OF THE SKY",
                                "กติกาขยะและสิทธิ์ทาง",
                                "ขยะ สิทธิ์ในวงโคจร",
                                teaches=["orbital rules debris"],
                                audience="คนที่สนใจกติกาการใช้วงโคจร",
                                intent_hints=["กติกาขยะอวกาศ"],
                                recommend_when=["policy"],
                                tags=["policy"],
                            ),
                        ],
                    ),
                    folder(
                        "build",
                        "BUILD",
                        "ทำให้ของจริง",
                        "จากโมเดลเป็นของที่ปล่อยได้",
                        [
                            course(
                                "make-it-flight-ready",
                                "MAKE IT FLIGHT-READY",
                                "สร้างให้บินได้",
                                "จากโมเดลเป็นของที่ปล่อยได้",
                                teaches=["flight readiness intuition"],
                                audience="คนที่อยากไปต่อจากบทเรียนสู่ของจริง",
                                intent_hints=["flight ready", "สร้างดาวเทียมจริง"],
                                recommend_when=["hardware", "build-satellite"],
                                tags=["build"],
                            ),
                            course(
                                "cleanroom-intuition",
                                "CLEANROOM INTUITION",
                                "ห้องสะอาดทำไม",
                                "ทำไมประกอบของบินไม่ใช่โต๊ะบ้าน",
                                teaches=["why cleanroom"],
                                audience="คนที่สนใจกระบวนการผลิต",
                                intent_hints=["cleanroom", "ห้องสะอาด"],
                                recommend_when=["hardware"],
                                tags=["build"],
                            ),
                        ],
                    ),
                    folder(
                        "go-farther",
                        "GO FARTHER",
                        "ไปต่อ",
                        "ค้างวงและการออกจากโลก",
                        [
                            course(
                                "staying-in-orbit",
                                "STAYING IN ORBIT",
                                "ทำไมถึงค้างบนฟ้าได้",
                                "แรงต้าน อายุขัย ขับดันค้างวง",
                                teaches=["lifetime drag propulsion intuition"],
                                audience="คนที่สนใจอายุภารกิจ",
                                intent_hints=["ทำไมดาวเทียมตกลงมา", "อายุวงโคจร"],
                                recommend_when=["orbits", "propulsion"],
                                tags=["orbits"],
                            ),
                            course(
                                "going-farther",
                                "GOING FARTHER",
                                "ออกจากวงโคจรโลก",
                                "ไปดวงจันทร์ / ลึกกว่า",
                                teaches=["leaving Earth orbit"],
                                audience="คนที่สนใจภารกิจไกล",
                                intent_hints=["ออกจากวงโคจรโลก"],
                                recommend_when=["deep-space"],
                                tags=["deep-space"],
                            ),
                        ],
                    ),
                ],
            ),
        ],
    }

    out = Path(__file__).resolve().parents[1] / "data" / "space" / "catalog.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
